# Generated by Django 5.2.6 on 2025-10-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_phone_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('BR', 'Brazil'), ('US', 'United States'), ('UK', 'United Kingdom'), ('ES', 'Spain'), ('JP', 'Japan'), ('AU', 'Australia')], default='BR'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
