# Generated by Django 5.2.6 on 2025-10-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(choices=[('BR', 'Brazil'), ('US', 'United States'), ('UK', 'United Kingdom'), ('ES', 'Spain'), ('JP', 'Japan'), ('AU', 'Australia')]),
        ),
    ]
