# Generated by Django 5.2.6 on 2025-09-18 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='num_people',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(),
        ),
    ]
