# Generated by Django 5.2.6 on 2026-07-07 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_alter_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)]),
        ),
    ]
